server: 
    port: 9031
    
eureka: 
    client: 
        register-with-eureka: false     #消费者不注册到注册中心
        #未配置fetch-registry: false，则默认为true即允许从注册中心获取微服务列表
        service-url: 
            defaultZone: http://eureka-server:9010/eureka/,http://eureka-server1:9011/eureka/,http://eureka-server2:9012/eureka/
            
#指定使用feign调用服务提供者时的负载均衡策略，默认是轮询。
micro-service-provider: 
    ribbon:
        NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
        
#其中“alh-tms”是服务提供者的名字指明对哪拨服务提供者进行负载均衡策略配置，修改策略时修改最后的类名即可。默认是轮询。
#alh-tms:
#    ribbon:
#        NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #配置规则 随机
#        NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
#        NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule #配置规则 重试
#        NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule #配置规则 响应时间权重
